name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: |
          - recursive: false
            args: [--no-frozen-lockfile]

    - name: lint
      run: pnpm -r lint

    - name: build
      run: pnpm -r build
